export const GET_NFT_ALL_COLLECTION = '@NFT_MANAGEMENT/GET_NFT_ALL_COLLECTION'
export const GET_NFT_ALL_ITEM = '@NFT_MANAGEMENT/GET_NFT_ALL_ITEM'
export const GET_DETAILS_NFT_ITEM = '@NFT_MANAGEMENT/GET_DETAILS_NFT_ITEM'
export const GET_DETAILS_NFT_COLLECTION = '@NFT_MANAGEMENT/GET_DETAILS_NFT_COLLECTION'